version: '3.8'

services:
  mongo-service:
    image: "mongo:5.0"  # Replace with the desired MongoDB version
    container_name: mongo-db
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: /path/to/your/mongo/config
        target: /etc/mongod.conf
        read_only: true
      - type: bind
        source: /path/to/your/certificates
        target: /etc/mongo-certs/
        read_only: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "securepassword"
    restart: always
    security_opt:
      - no-new-privileges:true

# MongoDB Configuration (mongod.conf)

# The MongoDB configuration file will be provided at the path `/path/to/your/mongo/config/mongod.conf`
# Example content for mongod.conf:

# storage:
#   dbPath: /data/db
#   journal:
#     enabled: true
# systemLog:
#   destination: file
#   logAppend: true
#   path: /var/log/mongodb/mongod.log
# net:
#   port: 27017
#   bindIp: 0.0.0.0
#   tls:
#     mode: requireTLS
#     certificateKeyFile: /etc/mongo-certs/server.pem
#     CAFile: /etc/mongo-certs/ca.pem
# security:
#   authorization: enabled
